### PR TITLE
Redesign

### LINKED ISSUE #5: Add a way to update the widget contents programmatically
Using `model.updateBuffer()` does not work because it gets blown away during the widget refresh.

### PR DESCRIPTION
**Pull request by blink1073**
This combines the efforts of @dwillmer and @jasongrout (from https://github.com/jupyter/jupyter-js-input-area).
Adds `filename`, `tabSize`, and `readOnly` to the discussed `ViewModel`.
Use `mimetype` to set the mode, or fall back on the `filename`.

Closes #5.

### CODE REVIEW

**Comment by blink1073** [comment]
cc @ellisonbg @sccolbert

**Comment by jasongrout** [comment]
Thanks for doing this.  FYI, my most recent work is at https://github.com/jasongrout/jupyter-js-input-area/tree/notebook (diff at https://github.com/jupyter/jupyter-js-input-area/compare/master...jasongrout:notebook - it looks like the changes are pretty minimal, and may not impact your work here).

**Comment by blink1073** [comment]
Thanks Jason, I'll rectify.

**Comment by blink1073** [comment]
I saw one applicable TODO, which I believe I implemented in bdb6d3c.

**Comment by dwillmer** [comment]
:+1

**Comment by dwillmer** [comment]
:+1:

**Pull request merged**
